#!/bin/bash

BASHRC_FILE=/home/$USER/.bashrc

LINE="export PATH=\$PATH:$PWD/bin"

grep "$LINE" $BASHRC_FILE >> /dev/null
if [ "$?" == "1" ]; then
	echo "Updating .bashrc file"
	echo "export $LINE" >> $BASHRC_FILE
fi

